---
title: "Learning Security Controls - Themes"
---

This is a Quarto website.

To learn more about Quarto websites visit <https://quarto.org/docs/websites>.

```{ojs}
//| echo: false
import { renderChart } from "@trebor/zoomable-voronoi-treemap"
```

```{ojs}
//| echo: false
md`### Themes`
```

```{ojs}
//| echo: false
data = {
  const flare = await d3.json(
    "https://raw.githubusercontent.com/vanHeemstraSystems/learning-security-controls-themes/main/data/themes.json"
  );
  return d3.hierarchy(flare).sum((d) => (d.children ? 0 : Math.random()));
}
```

```{ojs}
//| echo: false
__topicsChart = {
  return renderChart({
    data,
    size: { width, height: 400 }
  });
}
```

# Master Access Control

# Master Authentication & Authorization Management

# Master Content Filtering

# Master Network Segmentation

# Master Internet Access

# Master Access Logging & Monitoring

# Master Opt Out

# Master Data Labelling

# Master Contractual Agreements

# Master Conditional Access

# Master Security Hardening

# Master Plugins Control

# Master Marketplace / Model Store Control

# Master Geofencing

# Master Memory

# Master Data Sovereignity

# Master Prompt & Response Logging & Monitoring

# Master Configuration Drift Monitoring

# Master Acceptable Use Policy Responsible AI

# Master Malware Scanning

# Master Private Account Usage

# Master Copyright Infringement Scanning

# Master Company Owned Encryption Keys

# Master Encryption

# Master Intrusion Detection

# Master Back-up

# Master Model Theft